version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch    # kibana will start when elasticsearch has started

  api:
    build: ./backend
    container_name: api_container
    volumes:
      - ./backend:/home/backend
    ports:
      - 4000:4000
    environment: 
      FLASK_ENV: development
    depends_on:
      - elasticsearch        

  app:
    build: ./frontend
    container_name: app_container
    volumes:
      - ./frontend:/home/frontend
    ports:
      - 5000:5000
    environment: 
      FLASK_ENV: development
#      API_URL: http://localhost:4000
    depends_on:
      - api
  
volumes:
  elasticsearch-data: